(async()=>{
const colors={marina:'#087b9e',anchorage:'#1ca68c',harbour:'#7655b5',alternative:'#1ca68c',swim:'#f0a13d',highlight:'#e06a45'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const hav=(a,b)=>{const R=3440.065,r=Math.PI/180,x=(b.lat-a.lat)*r,y=(b.lon-a.lon)*r,q=Math.sin(x/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
try{
 const res=await fetch('data/kos-route.json',{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const d=await res.json(),by=Object.fromEntries(d.places.map(p=>[p.id,p])),route=d.route.map(id=>by[id]);
 let total=0;for(let i=1;i<route.length;i++)total+=hav(route[i-1],route[i]);document.getElementById('total').textContent=total.toFixed(1)+' sm';document.getElementById('count').textContent=d.places.length;
 const map=L.map('kos-map',{zoomControl:false,preferCanvas:true});L.control.zoom({position:'bottomright'}).addTo(map);
 L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,tileSize:256,zoomOffset:0,attribution:'© OpenStreetMap'}).addTo(map);
 const markers={};d.places.forEach((p,i)=>{const icon=L.divIcon({className:'',html:`<div style="width:30px;height:30px;background:${colors[p.type]};border:3px solid #fff;border-radius:50% 50% 50% 8px;transform:rotate(-45deg);box-shadow:0 3px 9px #00384f66"><span style="display:block;transform:rotate(45deg);text-align:center;line-height:24px;color:#fff">●</span></div>`,iconSize:[30,30],iconAnchor:[15,28]});markers[p.id]=L.marker([p.lat,p.lon],{icon}).addTo(map).bindPopup(`<b>${esc(p.name)}</b><br>${esc(p.stage)}<br><small>${esc(p.summary)}</small>`)});
 L.polyline(route.map(p=>[p.lat,p.lon]),{color:'#087b9e',weight:4,dashArray:'10 7'}).addTo(map);
 const cards=document.getElementById('cards');d.places.forEach((p,i)=>{const x=document.createElement('article');x.className='kos-card';x.id='card-'+p.id;x.innerHTML=`<div class="kos-head"><div class="kos-num" style="background:${colors[p.type]}">${i+1}</div><div><h2>${esc(p.name)}</h2><div class="kos-meta">${esc(p.stage)} · ${p.lat.toFixed(6)}, ${p.lon.toFixed(6)}</div>${p.verified?'':'<span class="kos-unverified">Planungsmarker, nicht verifiziert</span>'}</div></div><div class="kos-detail"><p>${esc(p.summary)}</p><h3>Highlights</h3><ul>${p.highlights.map(v=>`<li>${esc(v)}</li>`).join('')}</ul><h3>Hafen / Ankern</h3><p>${esc(p.berthing)}</p><p class="kos-note"><b>Skipperhinweis:</b> ${esc(p.note)}</p>${p.url?`<small>Quelle: <a href="${esc(p.url)}" target="_blank" rel="noopener">${esc(p.source)}</a></small>`:`<small>Quelle: ${esc(p.source)}</small>`}</div>`;x.onclick=()=>{document.querySelectorAll('.kos-card').forEach(c=>c.classList.remove('active'));x.classList.add('active');markers[p.id].openPopup();map.flyTo([p.lat,p.lon],12)};cards.appendChild(x)});
 const bounds=L.latLngBounds(d.places.map(p=>[p.lat,p.lon]));const fit=()=>{map.invalidateSize(false);map.fitBounds(bounds,{padding:[35,35]})};document.getElementById('fit').onclick=fit;fit();setTimeout(fit,250);window.addEventListener('resize',()=>map.invalidateSize(false));
 document.getElementById('kos-menu').onclick=()=>document.querySelector('.kos-panel').classList.toggle('open');
}catch(e){document.getElementById('cards').innerHTML=`<p class="kos-note"><b>Ladefehler:</b> ${esc(e.message)}</p>`;console.error(e)}
})();
